trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none   # we’ll just use the artifact from the build

# Step 1: download the artifact from the previous build pipeline
- download: current
  artifact: react-app
  displayName: 'Download React build artifact'

# Step 2: login to Azure manually using hardcoded credentials
- script: |
    echo "Logging into Azure..."
    az login --service-principal \
      -u <YOUR_CLIENT_ID> \
      -p <YOUR_CLIENT_SECRET> \
      --tenant <YOUR_TENANT_ID>
    echo "Setting subscription..."
    az account set --subscription <YOUR_SUBSCRIPTION_ID>
  displayName: 'Login to Azure'

# Step 3: deploy the build folder to your Azure Web App
- script: |
    echo "Deploying React app to Azure Web App..."
    az webapp deploy \
      --resource-group skill-anvil \
      --name azure-deploy-test \
      --src-path $(Pipeline.Workspace)/react-app
  displayName: 'Deploy React app'
